# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: My UX Journey
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Welcome to my official UX Apprentice Journey! It will always be a work in progress but the benfit will be seeing the things I have learned along the way. This means that each blog post will be something related to my design journey to becoming a full time
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  myuxjourney

# Build settings
markdown: kramdown
