# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: My UX Journey
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Starting my UX Apprenticeship and documenting my progress on this blog motivates me. It will provide an insight into my education and development as a UX designer. I'll record difficulties and discoveries, encompassing anything from interface design to user research. Join me on my journey as I develop into an effective UX Designer within the ever-evolving field of digital design.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username: myuxjourney

# Build settings
markdown: kramdown
